apiVersion: v1
kind: BuildConfig
metadata:
  name: rumblejake.inventory-management-svc-jr
  labels:
    app: inventory-management-svc-jr
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/rumblejake/inventory-management-svc-jr.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-jr
        - name: BRANCH
          value: master
